name: SCA SAST Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  BuildWithGitHubActions:
      uses: jpmtgit/reusable_template/.github/workflows/SCA_SAST_SECRETSCANNING.yml@main
      with: 
        file_path: test2.java
