name: SecretsHandling

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
  Demo_secrets:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.TOPSECRET }}
      run: |
       echo "Github"
       echo "$SUPER_SECRET"
