name: Secret Handling

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SecretHandling:
      uses: jpmtgit/reusable_template/.github/workflows/Secret_Scanning.yml@main
