name: Workflow using Secret Scan Template
on:
  push:
    branches: [main]

jobs:
  use_secret_scan_template:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.TOPSECRET }}  # Create an environment variable
    steps:
      - name: Use the secret scan template
        uses: jpmtgit/reusable_template/.github/workflows/Secret_Scanning.yml@main
        with:
          secret_var: ${{ env.SUPER_SECRET }}  # Use the environment variable
