name: Secret Handling

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  SecretHandling:
      uses: jpmtgit/reusable_template/.github/workflows/Secret_Handling.yml@main
