name: SecretsHandling

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
  Demo_secrets:
    uses: jpmtgit/reusable_template/.github/workflows/SecretHandling.yml@main
